No need to set password on 10.4+.

diff --git a/etc/service/mysql/run b/etc/service/mysql/run
--- a/etc/service/mysql/run
+++ b/etc/service/mysql/run
@@ -24,34 +24,33 @@ fi
 [ -f /etc/service/mysql/run.initialization ] && source /etc/service/mysql/run.initialization
 
 if [ -e /etc/init.d/mariadb ]; then
-  MYSQL="/etc/init.d/mariadb"
+  # There is no need to set debian-sys-maint password because with 10.4+ there is unix
+  # socket authentication instead (which on Ubuntu is when /etc/init.d/mariadb has been made).
 else
-  MYSQL="/etc/init.d/mysql"
-fi
+  # We set debian-sys-maint password which might be in this Docker image different for existing data.
 
-# We set debian-sys-maint password which might be in this Docker image different for existing data.
+  PASSWORD=$(grep password /etc/mysql/debian.cnf | awk '{print $3}' | head -1)
 
-PASSWORD=$(grep password /etc/mysql/debian.cnf | awk '{print $3}' | head -1)
+  # If any of the following commands fails we want to shutdown temporary MySQL instance.
+  trap "/etc/init.d/mysql stop" EXIT
 
-# If any of the following commands fails we want to shutdown temporary MySQL instance.
-trap "$MYSQL stop" EXIT
+  # Temporary MySQL instance with permissions disabled.
+  /usr/bin/mysqld_safe --skip-grant-tables --bind-address 127.0.0.1 --skip-syslog --log-error=/var/log/mysql/error.log &
 
-# Temporary MySQL instance with permissions disabled.
-/usr/bin/mysqld_safe --skip-grant-tables --bind-address 127.0.0.1 --skip-syslog --log-error=/var/log/mysql/error.log &
+  for i in $(seq 1 30); do
+    sleep 1
+    if /etc/init.d/mysql status > /dev/null ; then break; fi
+  done
 
-for i in $(seq 1 30); do
+  /usr/bin/mysql -u root -D mysql -e "update user set password=password('$PASSWORD') where user='debian-sys-maint'"
+
+  # Is there any other script to run here?
+  [ -f /etc/service/mysql/run.permissions ] && source /etc/service/mysql/run.permissions
+
+  /etc/init.d/mysql stop > /dev/null
+
+  # Wait a bit, so that all processes are really gone.
   sleep 1
-  if "$MYSQL" status > /dev/null ; then break; fi
-done
-
-/usr/bin/mysql -u root -D mysql -e "update user set password=password('$PASSWORD') where user='debian-sys-maint'"
-
-# Is there any other script to run here?
-[ -f /etc/service/mysql/run.permissions ] && source /etc/service/mysql/run.permissions
-
-"$MYSQL" stop > /dev/null
-
-# Wait a bit, so that all processes are really gone.
-sleep 1
+fi
 
 exec /usr/bin/mysqld_safe --skip-syslog --log-error=/var/log/mysql/error.log 2>&1 >> /var/log/mysql/error.log
